package com.niumi.coffeejournal

object TestTags {
    const val Calendar = "journal-calendar"
    const val CalendarBrandDisplayMode = "calendar-display-brand"
    const val CalendarCoffeeDisplayMode = "calendar-display-coffee"
    const val CalendarModeIndicator = "calendar-mode-indicator"
    const val PreviousMonth = "previous-month"
    const val NextMonth = "next-month"
    const val MonthSummaryCard = "month-summary-card"
    const val CalendarDayPrefix = "calendar-day-"
    const val CalendarDayNumberPrefix = "calendar-day-number-"
    const val CalendarCountBadgePrefix = "calendar-count-badge-"
    const val CalendarImagePrefix = "calendar-image-"
    const val RecordButton = "record-drink"
    const val MissingImagePrompt = "missing-image-prompt"
    const val ConfirmSave = "confirm-save"
    const val DiscardDraft = "discard-draft"
    const val RecordEditorScroll = "record-editor-scroll"
    const val MonthlySpend = "monthly-spend"
    const val BottomCalendarTab = "bottom-tab-咖啡日历"
    const val BottomCatalogTab = "bottom-tab-豆库"
    const val BottomInsightsTab = "bottom-tab-总结"
    const val RootScreenTitle = "root-screen-title"
    const val RootScreenSettings = "root-screen-settings"
    const val SettingsBack = "settings-back"
    const val ManualProductName = "manual-product-name"
    const val ManualProductPreview = "manual-product-preview"
    const val ChainBrandGrid = "chain-brand-grid"
    const val ChainBrandCardPrefix = "chain-brand-card-"
    const val BrandProductGrid = "brand-product-grid"
    const val BrandProductCardPrefix = "brand-product-card-"
}
